driver:
  name: vagrant
provisioner:
  name: chef_zero
  client_rb:
    audit_mode: MICHAEL_FOO
platforms:
  -
    name: ubuntu-12.04
  -
    name: centos-6.5
suites:
  -
    name: default
    run_list:
      - 'recipe[datasift-kafka::default]'
    attributes: null
