---
driver:
  name: docker
  require_chef_omnibus: '11.16.4'
  memory: '512m'

provisioner:
  name: chef_solo

platforms:
  - name: centos-6.4
    driver_config:
      provision_command: yum install -y tar
    attributes:
      java:
        jdk_version: 7
  - name: debian-7.4
    run_list:
      - recipe[apt]
    attributes:
      java:
        jdk_version: 7
  - name: ubuntu-14.04
    run_list:
      - recipe[apt]
    attributes:
      java:
        jdk_version: 7

suites:
  - name: init-style-sysv
    run_list:
      - recipe[java::default]
      - recipe[kafka::default]
    attributes:
      kafka:
        version: <%= ENV.fetch('KAFKA_VERSION', '0.8.1.1') %>
        scala_version: <%= ENV.fetch('SCALA_VERSION', '2.9.2') %>
        checksum: <%= ENV.fetch('KAFKA_CHECKSUM', '""') %>
        md5_checksum: <%= ENV.fetch('KAFKA_MD5', '""') %>
        ulimit_file: 128000
        broker:
          controlled_shutdown_enable: <%= ENV.fetch('KAFKA_CTRL_SHUTDOWN', nil) %>
          log_dirs: ['/mnt/kafka-logs-1', '/mnt/kafka-logs-2']
          zookeeper_connect: ['localhost:2181']
          zookeeper_connection_timeout_ms: 15_000

