language: ruby
script: bundle exec rake test
sudo: false
cache:
  - bundler
rvm:
  - 1.9.3
  - 2.0.0
  - 2.1.0
gemfile:
  - Gemfile
  - gemfiles/chef-11.4.4.gemfile
  - gemfiles/chef-11.6.2.gemfile
  - gemfiles/chef-11.8.2.gemfile
  - gemfiles/chef-11.10.4.gemfile
matrix:
  fast_finish: true
  exclude:
    - rvm: 2.0.0
      gemfile: gemfiles/chef-11.4.4.gemfile
    - rvm: 2.1.0
      gemfile: gemfiles/chef-11.4.4.gemfile
    - rvm: 2.0.0
      gemfile: gemfiles/chef-11.6.2.gemfile
    - rvm: 2.1.0
      gemfile: gemfiles/chef-11.6.2.gemfile
    - rvm: 2.0.0
      gemfile: gemfiles/chef-11.8.2.gemfile
    - rvm: 2.1.0
      gemfile: gemfiles/chef-11.8.2.gemfile
    - rvm: 2.0.0
      gemfile: gemfiles/chef-11.10.4.gemfile
    - rvm: 2.1.0
      gemfile: gemfiles/chef-11.10.4.gemfile
  allow_failures:
    - gemfile: gemfiles/chef-11.4.4.gemfile
