name             'webapp'
maintainer       'The Authors'
maintainer_email 'you@example.com'
license          'all_rights'
description      'Installs/Configures webapp'
long_description 'Installs/Configures webapp'
version          '0.1.0'

depends          'nodejs'
depends          'nginx'
