name             'twitterapi-reader'
maintainer       'The Authors'
maintainer_email 'ollie@ollieparsley.com'
license          'all_rights'
description      'Installs/Configures twitterapi-reader'
long_description 'Installs/Configures twitterapi-reader'
version          '0.1.0'

depends 'supervisor', '= 0.4.12'
depends 'java', '~> 1.31.0'
