source 'https://supermarket.chef.io'

cookbook 'java_se', '~> 8.60.2'
cookbook 'datasift-stats', path: 'cookbooks/datasift-stats'
cookbook 'datasift-kafka', path: 'cookbooks/datasift-kafka'
cookbook 'datasift-writer', path: 'cookbooks/datasift-writer'
cookbook 'gnip-reader', path: 'cookbooks/gnip-reader'
cookbook 'twitterapi-reader', path: 'cookbooks/twitterapi-reader'
cookbook 'historics-api', path: 'cookbooks/historics-api'
cookbook 'historics-reader', path: 'cookbooks/historics-reader'
cookbook 'webapp', path: 'cookbooks/webapp'
cookbook 'supervisor',
         git: 'https://github.com/poise/supervisor.git',
         branch: 'v0.4.12'
cookbook 'kafka',
         git: 'https://github.com/mthssdrbrg/kafka-cookbook.git',
         branch: 'v0.7.1'
cookbook 'influxdb',
         git: 'https://github.com/datasift/chef-influxdb.git',
         ref: '232e2afd4afb29b6eecb3369de84f1674272cd59'
cookbook 'cron', '~> 1.6.1'
cookbook 'nodejs', '~> 2.4.0'
